name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures GitHub Actions can create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Adjust this to your Go version

      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o go-cli-linux ./cmd/app/main.go
          GOOS=windows GOARCH=amd64 go build -o go-cli.exe ./cmd/app/main.go
          GOOS=darwin GOARCH=amd64 go build -o go-cli-mac ./cmd/app/main.go

      - name: Generate version tag
        id: generate_tag
        run: |
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)
          # Get the current date in YYYY-MM-DD format
          CURRENT_DATE=$(date +'%Y.%m.%d')
          # Create a version tag with date and commit hash
          VERSION="v${CURRENT_DATE}-${COMMIT_HASH}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VERSION_NUM=${CURRENT_DATE}-${COMMIT_HASH}" >> $GITHUB_ENV
          echo "Generated version: ${VERSION}"
          
      - name: Update README with new version links
        run: |
          # Use the generated version tag
          VERSION=${{ env.VERSION }}
          VERSION_NUM=${{ env.VERSION_NUM }}
          REPO_URL=$(echo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY})
          
          # Update README.md with new download links
          # Assuming README.md has sections for download links that we can update
          sed -i "s|Linux Binary: .*|Linux Binary: ${REPO_URL}/releases/download/${VERSION}/go-cli-linux|g" README.md
          sed -i "s|Windows Binary: .*|Windows Binary: ${REPO_URL}/releases/download/${VERSION}/go-cli.exe|g" README.md
          sed -i "s|macOS Binary: .*|macOS Binary: ${REPO_URL}/releases/download/${VERSION}/go-cli-mac|g" README.md
          sed -i "s|Version: .*|Version: ${VERSION_NUM}|g" README.md
          
          # Create the release notes from the updated README
          cat README.md > release_notes.md

      - name: Commit README changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update download links for ${GITHUB_REF#refs/tags/} release" || echo "No changes to commit"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: |
            go-cli-linux
            go-cli.exe
            go-cli-mac
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}