name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures GitHub Actions can create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Adjust this to your Go version

      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o go-cli-linux ./cmd/app/main.go
          GOOS=windows GOARCH=amd64 go build -o go-cli.exe ./cmd/app/main.go
          GOOS=darwin GOARCH=amd64 go build -o go-cli-mac ./cmd/app/main.go

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            go-cli-linux
            go-cli.exe
            go-cli-mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  